### ISSUE TITLE
레포지토리 이름 색상+컨트리뷰션 액티비티 색상 변경

### ISSUE THREAD

**Issue by myungseokang** [dhdh6190/colorGit#12]
커밋로그 색상만 변경되니 뭔가 어색해서 다른 부분도 색상을 바꿀 수 있게 하면 어떨까 싶습니다
![colorgit_issue](https://cloud.githubusercontent.com/assets/12431127/17542504/3ebabb5a-5f04-11e6-820d-d4415cff0edc.PNG)

**Comment by ddyokim** [comment]
오 예쁘네요! 일단 시간이 나는대로 작업해보겠습니다.
