### ISSUE TITLE
How about deploying this project to Chrome web store?

### ISSUE THREAD

**Issue by myungseokang** [dhdh6190/colorGit#24]
How about deploying this to [Chrome web store](https://chrome.google.com/webstore)?
I want to use this project :D

**Comment by ddyokim** [comment]
I'm very sorry for the late reply, i had a very important exam coming. The program has already been released in the chrome web store. But It needs some improvements so I'm planning to fix it during summer break. thank you! 
흑흑 확인 맨날 늦어서 미안합니다;_; 고시준비중이라 바빴어요...여름방학때 다시 고쳐 놓을게요!

**Comment by myungseokang** [comment]
@dhdh6190 아니에요!! 시험 수고 많으셨습니다. 👍
