### ISSUE TITLE
Maybe not releasing to web store

### ISSUE THREAD

**Issue by myungseokang** [dhdh6190/colorGit#26]
I saw your commit 6d235e1f5810a55be9f58835eee09c24a8164dca.
But it does not seem to have been released to the Chrome Web Store yet.

**Comment by ddyokim** [comment]
Fix it! Thank you!!
[다운로드](https://chrome.google.com/webstore/detail/mgmdjgnaodbpkoanmdbblaflilnhalig/publish-delayed?hl=ko)

**Comment by myungseokang** [comment]
@dhdh6190 Link raises 404 T.T

**Comment by ddyokim** [comment]
Sorry:0 I didn't notice that.

I think you may wait a few hours.

![image](https://user-images.githubusercontent.com/10115416/28155105-0f005e7c-67e8-11e7-9694-2b53d0866e9a.png)

**Comment by ddyokim** [comment]
SO sorry...!
Link has been changed.

[다운로드](https://chrome.google.com/webstore/detail/colorgit/mgmdjgnaodbpkoanmdbblaflilnhalig?hl=ko)

ㅋㅋㅋㅋ으악. 아니네요 안 바뀌었어요. 방금 막 업로드 완료되었나봐요.

**Comment by myungseokang** [comment]
Oh, I got it. confirmed. Thx!

넵넵! 확인했어요! 수고 많으셨습니다.
