### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by arine** [dhdh6190/colorGit#5]
Please write readme file =)

**Comment by ddyokim** [comment]
OK! But I can't write English very well.ㅠㅠ
How to write readme file?

**Comment by taeguk** [comment]
Make "README.md" in repo. root directory.

**Comment by ddyokim** [comment]
@taeguk Oh, It's too hard. plz help me

**Comment by taeguk** [comment]
@dhdh6190 I explained a few days ago! 
I recommend that you choose a model repo. of your colorGit and imitate that.
https://github.com/taeguk/vim-taeguk/blob/master/README.md
https://raw.githubusercontent.com/taeguk/vim-taeguk/master/README.md
I recommend this README.md. Try imitate this.
http://www.markdowntutorial.com/
Read the above link. It can be helpful for you~
